services:
  ingestor:
    image: ghcr.io/swissopenem/ingestor:${INGESTOR_VERSION:-latest}
    pull_policy: always
    networks:
      - ingestor-net
    ports:
      - ${INGESTOR_PORT:-8080}:8080
    environment:
      - "GIN_MODE=${GIN_MODE:-release}"
      - INGESTOR_SERVICE_USER_NAME
      - INGESTOR_SERVICE_USER_PASS
    user: "${UID:-0}:${GID:-0}"
    configs:
      - source: openem-ingestor-config.yaml
        target: /app/openem-ingestor-config.yaml
    restart:
      unless-stopped
    volumes:
      - ${HOST_COLLECTION_PATH?No HOST_COLLECTION_PATH specified}:${HOST_COLLECTION_PATH}:ro

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ingestor${DEPLOYMENT:+-${DEPLOYMENT}}.entrypoints=websecure"
      - "traefik.http.services.ingestor${DEPLOYMENT:+-${DEPLOYMENT}}.loadbalancer.server.port=8080"
      - "traefik.http.routers.ingestor${DEPLOYMENT:+-${DEPLOYMENT}}.tls=true"
      # Route //INGESTOR_DOMAIN/INGESTOR_PATH_PREFIX
      - "traefik.http.routers.ingestor${DEPLOYMENT:+-${DEPLOYMENT}}.rule=Host(`${INGESTOR_DOMAIN}`)${INGESTOR_PATH_PREFIX:+ && PathPrefix(`${INGESTOR_PATH_PREFIX}`)}"
      # Strip INGESTOR_PATH_PREFIX
      - "${INGESTOR_PATH_PREFIX:+traefik.http.middlewares.strip${DEPLOYMENT:+-${DEPLOYMENT}}.stripprefix.prefixes=${INGESTOR_PATH_PREFIX}}"
      - "${INGESTOR_PATH_PREFIX:+traefik.http.routers.ingestor${DEPLOYMENT:+-${DEPLOYMENT}}.middlewares=strip${DEPLOYMENT:+-${DEPLOYMENT}}@docker}"


networks:
  ingestor-net:
    external: true


configs:
  openem-ingestor-config.yaml:
    content: |
      Scicat:
        Host: ${SCICAT_BACKEND_URL:?No SCICAT_BACKEND_URL specified}/api/v3
      Transfer:
        StorageLocation: PSI
        Method: ${TRANSFER_METHOD:-ExtGlobus}
        ExtGlobus:
          TransferServiceUrl: ${GLOBUS_TRANSFER_PROXY_URL:-}
          SrcFacility: ${GLOBUS_SOURCE_FACILITY:-}
          DstFacility: ${GLOBUS_DESTINATION_FACILITY:-}
          CollectionRootPath: ${GLOBUS_COLLECTION_ROOT_PATH:-${HOST_COLLECTION_PATH}}

      MetadataExtractors:
        InstallationPath: ./extractors/
        SchemasLocation: ./schemas/
        Extractors:
          - Name: LS
            GithubOrg: osc-em
            GithubProject: oscem-extractor-life
            Version: v2.0.2
            Executable: oscem-extractor-life
            Checksum: a596ade8dd115b57fb8d5aad56b96b0e0ad2820bf57252443c21d4c80278ca6e
            ChecksumAlg: sha256
            CommandLineTemplate: "-i '{{.SourceFolder}}' -o '{{.OutputFile}}' ${LIFESCIENCE_EXTRACTOR_ADDITIONAL_PARAMS:-}"
            Methods:
              - Name: Single Particle
                Schema: oscem_schemas_spa.schema.json
                Url: https://w3id.org/oscem-schemas/latest/spa/jsonschema/oscem_schemas_spa.schema.json
              - Name: Cellular Tomography
                Schema: oscem_cellular_tomo.json
                Url: https://w3id.org/oscem-schemas/latest/cellular_tomo/jsonschema/oscem_schemas_cellular_tomo.schema.json
              - Name: Subtomogram Averaging
                Schema: oscem_tomo.json
                Url: https://w3id.org/oscem-schemas/latest/subtomo/jsonschema/oscem_schemas_subtomo.schema.json
              - Name: Environmental Tomography
                Schema: oscem_env_tomo.json
                Url: https://w3id.org/oscem-schemas/latest/env_tomo/jsonschema/oscem_schemas_env_tomo.schema.json

          - Name: MS
            GithubOrg: osc-em
            GithubProject: oscem-extractor-materials
            Version: v1.0.5
            Executable: oscem-extractor-materials
            Checksum: 47dc7f1fcb4bd51b10ac22d017d69838b671babb45c12bef6c9008d98d47e9f1
            ChecksumAlg: sha256
            CommandLineTemplate: "-i '{{.SourceFolder}}' -o '{{.OutputFile}}'"
            Methods:
              - Name: Material Science
                Schema: oscem_general.json
                Url: https://w3id.org/oscem-schemas/latest/general/jsonschema/oscem_schemas_general.schema.json

      WebServer:
        Auth:
          Disable: false
          Frontend:
            Origin: ${SCICAT_FRONTEND_URL:?No SCICAT_FRONTEND_URL specified}
            RedirectPath: "/ingestor"
          SessionDuration: 28800
          OAuth2:
            ClientID: "${OIDC_CLIENT_ID:-openem-ingestor-${FACILITY:?Either set OIDC_CLIENT_ID or FACILITY}}"
            RedirectURL: "https://${INGESTOR_DOMAIN?No INGESTOR_DOMAIN specified}${INGESTOR_PATH_PREFIX:-}/callback"
            Scopes:
              - email
          OIDC:
            IssuerURL: "${OIDC_ISSUER:?No OIDC_ISSUER specified}"
          JWT:
            UseJWKS: true
            JwksURL: "${OIDC_ISSUER}/protocol/openid-connect/certs"
            JwksSignatureMethods:
              - RS256
          RBAC:
            AdminRole: "ingestor-admin"
            CreateModifyTasksRole: "ingestor-write"
            ViewTasksRole: "ingestor-read"
        Paths:
          CollectionLocations:
            "${HOST_COLLECTION_NAME:-Data Root}": "${HOST_COLLECTION_PATH}"
        MetadataExtJobs:
          ConcurrencyLimit: 4
          QueueSize: 200
        Other:
          BackendAddress: https://${INGESTOR_DOMAIN}${INGESTOR_PATH_PREFIX:-}
          Port: ${PORT:-8080}
          SecureCookies: true
          LogLevel: ${LOG_LEVEL:-Info}
          DisableServiceAccountCheck: true
